=== haresrv/Net-Centric-Programming/Lab-8/email.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT email (from,to,content)>
<!ELEMENT content (#PCDATA|exercises|person)*>
<!ELEMENT exercises (exercise+)>
<!ELEMENT exercise (topic,description)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT person (#PCDATA)>

=== haresrv/Net-Centric-Programming/Lab-8/email.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email SYSTEM "email.dtd">
<email>
	<from> abc@gmail.com </from>
	<to> xyz@gmail.com </to>
	<content>
		<exercises>
			<exercise>
				<topic> DTD </topic>
				<description> From Instance to DTD </description>
			</exercise>
			<exercise>
				<topic> XSD</topic>
				<description> From Instance to Schema</description>
			</exercise>
		</exercises>
		Best Regards,
		<person> ABC </person>
	</content>
</email>
