=== haresrv/Net-Centric-Programming/Lab-8/studentreportXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.example.org/studentreportXMLSchema" 
 xmlns:tns="http://www.example.org/studentreportXMLSchema" 
 elementFormDefault="qualified">

<complexType name="studentType">
	<sequence>
		<element name="Name" type="string"></element>
		<element name="id" type="string"></element>
		<element name="study" type="tns:studyType"></element>
	</sequence>
</complexType>

<complexType name="studyType">
	<sequence>
		<element name="courses" type="tns:coursesType"></element>
	</sequence>
	<attribute name="year" type="tns:year" use="required">
	</attribute>
</complexType>

<complexType name="coursesType">
	<sequence>
		<element name="course" minOccurs="1" maxOccurs="unbounded" type="tns:courseType"></element>
	</sequence>
</complexType>

<complexType name="courseType">
	<sequence>
		<element name="name" type="string"></element>
		<element name="shortform" type="string"></element>
		<element name="report" type="tns:reportType" minOccurs="0" maxOccurs="unbounded"></element>
	</sequence>
</complexType>

<complexType name="reportType">
	<choice>
		<element name="grade" type="string"></element>
		<element name="date" type="string"></element>
	</choice>
</complexType>

<simpleType name="year">
   <restriction base="int">
      <pattern value="\d{4}"/>
   </restriction>
</simpleType>


<element name="xsdstudent" type="tns:studentType" ></element>

</schema>

=== haresrv/Net-Centric-Programming/Lab-8/studrep.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:xsdstudent 
xmlns:tns="http://www.example.org/studentreportXMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.example.org/studentreportXMLSchema studentreportXMLSchema.xsd ">
  <tns:Name>Abinaya</tns:Name>
  <tns:id>30082084</tns:id>
  <tns:study year="2000">
    <tns:courses>
      <tns:course>
        <tns:name>Computer Networks</tns:name>
        <tns:shortform>CN</tns:shortform>
        <tns:report>
          <tns:grade>A+</tns:grade>
        </tns:report>
      </tns:course>
    </tns:courses>
  </tns:study>
</tns:xsdstudent>
