=== haresrv/Net-Centric-Programming/Lab-8/studentreport.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT student (Name,id,study) >
<!ELEMENT study (courses) >
<!ELEMENT courses (course+) >
<!ELEMENT course (name+,shortform,report?) >
<!ELEMENT report (grade,date)* >
<!ELEMENT Name (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT shortform (#PCDATA)>
<!ATTLIST courses year CDATA #REQUIRED>

=== haresrv/Net-Centric-Programming/Lab-8/studentreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentreport SYSTEM "studentreport.dtd">
<student>
	<Name>Abinaya</Name>
	<id>30082084</id>
	<study>
		<courses year="2000">
			<course>
				<name> Computer Networks </name>
				<shortform>CN</shortform>
				<report>
					<grade>A+</grade>
					<date>2020-07-01</date>
				</report>
			</course>
			<course>
				<name>Theory of Computation</name>
				<shortform>TOC</shortform>
			</course>
		</courses>
	</study>
</student>
